version: '3.7'

services:
  frontend-app:
    build: .
    env_file:
      - ./.env.staging
    volumes:
      - ./.env.staging:/opt/streamtv-frontend/.env.staging
      - ./package.json:/opt/streamtv-frontend/package.json
      - ./package-lock.json:/opt/streamtv-frontend/package-lock.json
      - ./tsconfig.json:/opt/streamtv-frontend/tsconfig.json
      - ./src:/opt/streamtv-frontend/src
      - ./public:/opt/streamtv-frontend/public
      - ./.docker/node_modules:/opt/streamtv-frontend/node_modules
      - ./.git:/opt/streamtv-frontend/.git
      - ~/.gitconfig:/etc/gitconfig
      - ~/.ssh:/root/.ssh
      - $STREAM_TV_APP_CACHE:/opt/streamtv/var/cache
    working_dir: /opt/streamtv-frontend
    entrypoint: |
      /bin/sh -c 'npm install; npm run deploy'