version: '3.7'

services:
  frontend-app:
    build: .
    volumes:
      - ./streamtv:/opt/streamtv
      - ./src:/opt/streamtv-frontend/src
      - ./public:/opt/streamtv-frontend/public
      - ./.env.staging:/opt/streamtv-frontend/.env.staging
      - ./package.json:/opt/streamtv-frontend/package.json
      - ./package-lock.json:/opt/streamtv-frontend/package-lock.json
      - ./tsconfig.json:/opt/streamtv-frontend/tsconfig.json
      - ./.docker/node_modules:/opt/streamtv-frontend/node_modules
    working_dir: /opt/streamtv-frontend
    ports:
      - 3000:3000
    entrypoint: |
      /bin/sh -c 'npm install; npm start'