# Base configuration
# Not usable as is, needs an environment overlay

# apiVersion and kind of Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - streamtv-frontend/deployment.yaml
  - streamtv-frontend/hpa.yaml
  - streamtv-frontend/ingress.yaml
  - streamtv-frontend/service.yaml
