apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamtv-frontend
  namespace: streamtv
  labels:
    app: streamtv-frontend
  annotations:
    fluxcd.io/automated: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamtv-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: streamtv-frontend
    spec:
      containers:
        - name: streamtv-frontend
          image: fr0z3nk0/streamtv-frontend:latest
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: streamtv-frontend-config
          volumeMounts:
            - mountPath: "/usr/share/nginx/html/data"
              name: streamtv-data
      volumes:
        - name: streamtv-data
          persistentVolumeClaim:
            claimName: streamtv-data
