apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: streamtv-frontend
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: streamtv-frontend
  targetCPUUtilizationPercentage: 100
