name: CI

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm run build
      - name: docker build
        uses: actions/docker/cli@master
        with:
          args: build -t fr0z3nk0/streamtv-frontend
      - name: docker login
        uses: actions/docker/login@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - name: docker push
        uses: actions/docker/cli@master
        with:
          args: push fr0z3nk0/streamtv-frontend